-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


DROP TABLE IF EXISTS public."Caja";

CREATE TABLE IF NOT EXISTS public."Caja"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    monto integer NOT NULL,
    "fechaIni" date NOT NULL,
    "fechaFin" date NOT NULL,
    "isActive" boolean NOT NULL,
    "id_Usuario" integer NOT NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public."Color";

CREATE TABLE IF NOT EXISTS public."Color"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "R" integer NOT NULL,
    "G" integer NOT NULL,
    "B" integer NOT NULL,
    "id_Negocio" integer NOT NULL,
    CONSTRAINT "Color_pkey" PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public."Comanda";

CREATE TABLE IF NOT EXISTS public."Comanda"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    fecha date NOT NULL,
    "isActive" boolean NOT NULL,
    "id_Mesa" integer NOT NULL,
    CONSTRAINT "Comanda_pkey" PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public."ComandaDeta";

CREATE TABLE IF NOT EXISTS public."ComandaDeta"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    fecha date NOT NULL,
    "id_Item" integer NOT NULL,
    "id_Comanda" integer NOT NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public."Item";

CREATE TABLE IF NOT EXISTS public."Item"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(255) COLLATE pg_catalog."default" NOT NULL,
    precio integer NOT NULL,
    img character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "isActive" boolean NOT NULL,
    "id_ItemCateg" integer NOT NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public."ItemCateg";

CREATE TABLE IF NOT EXISTS public."ItemCateg"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "id_TipoAlimento" integer NOT NULL,
    CONSTRAINT "ItemCateg_pkey" PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public."Mesa";

CREATE TABLE IF NOT EXISTS public."Mesa"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "isActive" boolean NOT NULL,
    "id_Negocio" integer NOT NULL,
    CONSTRAINT "Mesa_pkey" PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public."Negocio";

CREATE TABLE IF NOT EXISTS public."Negocio"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    rut character(12) COLLATE pg_catalog."default" NOT NULL,
    direccion character varying(255) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(255) COLLATE pg_catalog."default",
    logo character varying(255) COLLATE pg_catalog."default",
    "isActive" boolean NOT NULL,
    CONSTRAINT "Negocio_pkey" PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public."Salida";

CREATE TABLE IF NOT EXISTS public."Salida"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    fecha date NOT NULL,
    "id_Caja" integer NOT NULL,
    CONSTRAINT "Salida_pkey" PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public."SalidaDeta";

CREATE TABLE IF NOT EXISTS public."SalidaDeta"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "id_Item" integer NOT NULL,
    "nom_Item" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "precio_Item" integer NOT NULL,
    cant integer NOT NULL,
    "id_Salida" integer NOT NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public."TipoAlimento";

CREATE TABLE IF NOT EXISTS public."TipoAlimento"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    img character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "isActive" boolean NOT NULL,
    "id_Negocio" integer NOT NULL,
    CONSTRAINT "TipoAlimento_pkey" PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public."Usuario";

CREATE TABLE IF NOT EXISTS public."Usuario"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombres character varying(100) COLLATE pg_catalog."default" NOT NULL,
    apellidos character varying(100) COLLATE pg_catalog."default" NOT NULL,
    correo character varying(100) COLLATE pg_catalog."default",
    usuario character varying(100) COLLATE pg_catalog."default" NOT NULL,
    clave character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "isActive" boolean NOT NULL,
    "id_Rol" integer NOT NULL,
    "id_Negocio" integer NOT NULL,
    CONSTRAINT "Usuario_pkey" PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public."Rol";

CREATE TABLE IF NOT EXISTS public."Rol"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    nombre character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."Caja"
    ADD FOREIGN KEY ("id_Usuario")
    REFERENCES public."Usuario" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Color"
    ADD FOREIGN KEY ("id_Negocio")
    REFERENCES public."Negocio" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Comanda"
    ADD FOREIGN KEY ("id_Mesa")
    REFERENCES public."Mesa" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."ComandaDeta"
    ADD FOREIGN KEY ("id_Comanda")
    REFERENCES public."Comanda" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Item"
    ADD FOREIGN KEY ("id_ItemCateg")
    REFERENCES public."ItemCateg" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."ItemCateg"
    ADD FOREIGN KEY ("id_TipoAlimento")
    REFERENCES public."TipoAlimento" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Mesa"
    ADD FOREIGN KEY ("id_Negocio")
    REFERENCES public."Negocio" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Salida"
    ADD FOREIGN KEY ("id_Caja")
    REFERENCES public."Caja" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."SalidaDeta"
    ADD FOREIGN KEY ("id_Salida")
    REFERENCES public."Salida" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."TipoAlimento"
    ADD FOREIGN KEY ("id_Negocio")
    REFERENCES public."Negocio" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Usuario"
    ADD FOREIGN KEY ("id_Negocio")
    REFERENCES public."Negocio" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Usuario"
    ADD FOREIGN KEY ("id_Rol")
    REFERENCES public."Rol" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;